Math-magicians: Events
ntzwilly/math-magicians pull request #3
Opened 2021-10-20 14:34 UTC by ntzwilly

## Description:

- Add **calculate.js** and **operate.js** into a **logic/** directory
- Import the files in the Calculator component.
- Implement the event handlers.
- Test the app in the browser.

2021-10-20 15:02 UTC, Emmyn5600 requested changes
Hi,

Good job so far! 👏🏼 @ntzwilly 

Descriptive commit messages :heavy_check_mark:
Well written PR :heavy_check_mark:

There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: CHANGES REQUESTED :recycle:


### Changes requested.

- _Check the comment under the review_

 #### Optional suggestions
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-10-20 15:02 UTC, Emmyn5600 commented on src/logic/operate.js
> +  }
- [x] Kindly, display the user-friendly message once a user divides a number by zero 

![date-1](https://user-images.githubusercontent.com/55635977/138118583-2f1aaece-0e01-4509-aa78-8f4b940d7f77.png)

2021-10-20 16:50 UTC, ntzwilly commented on src/logic/operate.js
> +  }
Hi @Emmyn5600 , Thank you for your feedback.

However, I think this issue is not part of the requirements. These files (**calculate.js** and **operate.js**) were provided to us. We only need to use their logic in order to implement the event handlers for the Calculator component. All math operations are working and the error message is the default, not my implementation.
![error_message](https://user-images.githubusercontent.com/9049260/138135880-43eee925-3a87-4cbd-b30d-466ee2079ce0.png)
Kindly have a second look at this as we have a limited number of code reviews.

2021-10-21 08:34 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @ntzwilly, 

Everything looks good to me. Well Done.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-21 08:49 UTC, merged